language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sunil28/starbucks-frontend .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test